spring:
  application:
    name: FureverFriends
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/testdb
    username: name
    password: password
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
jwt:
  key: some-very-secret-key-for-dev-to-use #${JWT_KEY}
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000
pagination:
  page-size: 10
springdoc:
  paths-to-match: "/api/**"
  swagger-ui:
    enabled: true
  packages-to-scan: org.example.fureverfriends